name: test
on:
  push:
    branches:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - name: Lint Package with Biome
        run: deno task lint