name: test
on:
  push:
  pull_request:

jobs:
  test-deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["1.x"]
    name: Test Deno on Version ${{ matrix.deno }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run tests in Deno
        run: deno test -A
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["1.x"]
        node: ["20", "21"]
    name: Test Node on Version ${{ matrix.node }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Build and test node
        run: deno task npm 0.0.0
